character(len=*),parameter :: version = "@version@"
character(len=*),parameter :: commit = "@commit@"
character(len=*),parameter :: date = "@date@"
character(len=*),parameter :: author = "'@author@@@origin@'"
character(len=*),parameter :: fcompiler = "@fcid@ @fcver@"
character(len=*),parameter :: ccompiler = "@ccid@ @ccver@"
character(len=*),parameter :: bsystem = "@bsystem@"
character(len=*),parameter :: tomlfvar = "@tomlfvar@"
character(len=*),parameter :: gfn0var = "@gfn0var@"
character(len=*),parameter :: gfnffvar = "@gfnffvar@"
character(len=*),parameter :: tblitevar = "@tblitevar@"
character(len=*),parameter :: xhcffvar = "@xhcffvar@"
character(len=*),parameter :: lwoniomvar = "@lwoniomvar@"
