name: "Close stale issues and PRs"

on:
  schedule:
    # Every day at 00:00
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v9.0.0
        with:
          stale-issue-message: 'This issue had no activity for **6 months**. It will be closed in **1 week** unless there is some new activity.'
          stale-issue-label: 'stale'
          exempt-issue-labels: 'bug,enhancement'
          stale-pr-message: 'This pull request had no activity for **6 months**. It will be closed in **1 week** unless there is some new activity.'
          stale-pr-label: 'stale'
          days-before-stale: 180
          days-before-close: 7
          operations-per-run: 20
